### ISSUE TITLE
NullableMarkdownEditorValueConverter and NullableRteMacroRenderingValueConverter

### ISSUE THREAD

**Issue by erikjanwestendorp** [JasonElkin/Emptiness#2]
Is it an idea to implement a `NullableMarkdownEditorValueConverter` and a `NullableRteMacroRenderingValueConverter` as suggested in [this ](https://github.com/umbraco/Umbraco-CMS/pull/13747#issuecomment-1431595159)comment? 

If desired, I want to work on this but I wonder if there is a chance that this will be merged?

**Comment by JasonElkin** [comment]
Hi @erikjanwestendorp, thanks so much for your interest, but I think this is out of scope for this package.

All Emptiness is concerned with is making sure that values that can be null in the Backoffice, are still null when they come out the other side of the property value converter. 

This is already the case for Markdown and RTE properties - they return `null` if there's nothing in them.
